-- Phase 10 will execute these DML statements one at a time through a Python
-- connector configured with paramstyle='qmark'. Each ? is a bound batch ID.
-- The staged row insert itself uses executemany() and the same qmark binding.
-- This file documents the exact final-publication transaction; it is not a
-- standalone worksheet script and has not been executed against Snowflake.

BEGIN TRANSACTION;

-- One target schema corresponds to one deployment/profile. Replacing the
-- staged batch's complete month window removes stale keys from source revisions.
DELETE FROM HOUSING_ANALYTICS.FCT_HOUSING_MONTHLY
WHERE REFERENCE_MONTH BETWEEN
    (
        SELECT MIN(REFERENCE_MONTH)
        FROM HOUSING_ANALYTICS.STG_HOUSING_MONTHLY
        WHERE LOAD_BATCH_ID = ?
    )
    AND
    (
        SELECT MAX(REFERENCE_MONTH)
        FROM HOUSING_ANALYTICS.STG_HOUSING_MONTHLY
        WHERE LOAD_BATCH_ID = ?
    );

INSERT INTO HOUSING_ANALYTICS.FCT_HOUSING_MONTHLY (
    REFERENCE_MONTH,
    CMA_CODE,
    DWELLING_TYPE,
    HOUSING_STARTS,
    HOUSING_COMPLETIONS,
    HOUSING_UNDER_CONSTRUCTION,
    ACTIVITY_MEASURE_COUNT,
    HAS_ACTIVITY_DATA,
    ACTIVITY_RELEASE_TIMESTAMP,
    ACTIVITY_ARCHIVE_SHA256,
    STARTS_HOMEOWNER,
    STARTS_RENTAL,
    STARTS_CONDOMINIUM,
    STARTS_COOPERATIVE,
    STARTS_OTHER_MARKET,
    MARKET_MEMBER_COUNT,
    HAS_MARKET_DATA,
    MARKET_RELEASE_TIMESTAMP,
    MARKET_ARCHIVE_SHA256,
    GEOGRAPHY,
    HAS_COMPLETE_ACTIVITY,
    HAS_COMPLETE_MARKET_BREAKDOWN,
    MARKET_STARTS_TOTAL,
    NEW_HOUSING_PRICE_INDEX,
    NEW_HOUSE_PRICE_INDEX,
    NEW_LAND_PRICE_INDEX,
    PRICE_INDEX_COMPONENT_COUNT,
    PRICE_RELEASE_TIMESTAMP,
    PRICE_ARCHIVE_SHA256,
    HAS_PRICE_INDEX_DATA,
    HAS_COMPLETE_PRICE_INDEX,
    RESIDENTIAL_PERMIT_VALUE_DOLLARS,
    PERMIT_RELEASE_TIMESTAMP,
    PERMIT_ARCHIVE_SHA256,
    HAS_PERMIT_DATA,
    COMPLETION_TO_START_RATIO,
    STARTS_3_MONTH_AVERAGE,
    STARTS_YEAR_OVER_YEAR_PCT,
    UNDER_CONSTRUCTION_MONTH_CHANGE,
    HAS_12_MONTH_ANOMALY_BASELINE,
    STARTS_PRIOR_12_MONTH_AVERAGE,
    STARTS_PRIOR_12_MONTH_STDDEV,
    STARTS_ANOMALY_ZSCORE,
    STARTS_ANOMALY_FLAG,
    REFERENCE_YEAR,
    SOURCE_LOAD_BATCH_ID,
    SOURCE_VALIDATION_PROFILE,
    CREATED_AT_UTC,
    UPDATED_AT_UTC
)
SELECT
    REFERENCE_MONTH,
    CMA_CODE,
    DWELLING_TYPE,
    HOUSING_STARTS,
    HOUSING_COMPLETIONS,
    HOUSING_UNDER_CONSTRUCTION,
    ACTIVITY_MEASURE_COUNT,
    HAS_ACTIVITY_DATA,
    ACTIVITY_RELEASE_TIMESTAMP,
    ACTIVITY_ARCHIVE_SHA256,
    STARTS_HOMEOWNER,
    STARTS_RENTAL,
    STARTS_CONDOMINIUM,
    STARTS_COOPERATIVE,
    STARTS_OTHER_MARKET,
    MARKET_MEMBER_COUNT,
    HAS_MARKET_DATA,
    MARKET_RELEASE_TIMESTAMP,
    MARKET_ARCHIVE_SHA256,
    GEOGRAPHY,
    HAS_COMPLETE_ACTIVITY,
    HAS_COMPLETE_MARKET_BREAKDOWN,
    MARKET_STARTS_TOTAL,
    NEW_HOUSING_PRICE_INDEX,
    NEW_HOUSE_PRICE_INDEX,
    NEW_LAND_PRICE_INDEX,
    PRICE_INDEX_COMPONENT_COUNT,
    PRICE_RELEASE_TIMESTAMP,
    PRICE_ARCHIVE_SHA256,
    HAS_PRICE_INDEX_DATA,
    HAS_COMPLETE_PRICE_INDEX,
    RESIDENTIAL_PERMIT_VALUE_DOLLARS,
    PERMIT_RELEASE_TIMESTAMP,
    PERMIT_ARCHIVE_SHA256,
    HAS_PERMIT_DATA,
    COMPLETION_TO_START_RATIO,
    STARTS_3_MONTH_AVERAGE,
    STARTS_YEAR_OVER_YEAR_PCT,
    UNDER_CONSTRUCTION_MONTH_CHANGE,
    HAS_12_MONTH_ANOMALY_BASELINE,
    STARTS_PRIOR_12_MONTH_AVERAGE,
    STARTS_PRIOR_12_MONTH_STDDEV,
    STARTS_ANOMALY_ZSCORE,
    STARTS_ANOMALY_FLAG,
    REFERENCE_YEAR,
    LOAD_BATCH_ID,
    VALIDATION_PROFILE,
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP()
FROM HOUSING_ANALYTICS.STG_HOUSING_MONTHLY
WHERE LOAD_BATCH_ID = ?;

UPDATE HOUSING_ANALYTICS.ELT_LOAD_AUDIT
SET
    STATUS = 'SUCCEEDED',
    PUBLISHED_ROW_COUNT = (
        SELECT COUNT(*)
        FROM HOUSING_ANALYTICS.STG_HOUSING_MONTHLY
        WHERE LOAD_BATCH_ID = ?
    ),
    COMPLETED_AT_UTC = CURRENT_TIMESTAMP()
WHERE LOAD_BATCH_ID = ?;

COMMIT;

-- The loader issues ROLLBACK explicitly if any DML statement above fails, then
-- updates the audit row to FAILED outside the rolled-back transaction.
